name: Update GTA V Signature Database

on:
  schedule:
    - cron: '0 16 * * *'  # Runs every day at 4pm UTC (12pm EST)
  workflow_dispatch:
  push:
    branches:
      - main 

jobs:
  update-signatures:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the gtav-sigscan tool
        uses: actions/checkout@v2
        with:
          repository: yubie-re/gtav-sigscan
          path: gtav-sigscan

      - name: Install C++ compiler and CMake
        run: |
          sudo apt-get update
          sudo apt-get install -y g++ cmake ninja-build

      - name: Clone private repository using PAT
        run: |
          git clone https://x-access-token:${{ secrets.GTA_SAMPLE_PAT }}@github.com/yubie-re/gta5-sig-samples.git files
          rm -rf files/.git
        working-directory: gtav-sigscan

      - name: Build the gtav-sigscan tool
        run: |
          cd gtav-sigscan
          cmake -S . -B build -G Ninja
          cmake --build build


      - name: Run the gtav-sigscan tool to generate new signatures
        run: |
          ./build/src/sigscan -savejson > /dev/null 2>&1
        working-directory: gtav-sigscan

      - name: Checkout the gta-sig-db repository
        uses: actions/checkout@v4
        with:
          path: gta-sig-db

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Copy new signatures to gta-sig-db and deduplicate
        run: |
          cp ../../gtav-sigscan/signatures.json ./signatures.json
          python ./update_signatures.py
        working-directory: gta-sig-db/sig-workflow

      - name: Commit and push changes if there are updates
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add sig-workflow/sig_db.json
          if git diff --staged --quiet; then
            echo "No changes to sig_db.json"
          else
            git commit -m "Update sig_db.json with new data"
            git push https://${{ secrets.GITHUB_TOKEN }}@github.com/yubie-re/gta-sig-db.git
          fi
        working-directory: gta-sig-db